### ISSUE TITLE
Is this still low level?

### ISSUE THREAD

**Issue by Borwe** [near/near-jsonrpc-client-rs#104]
Kindly assist, as I was looking for a rust api for near, and came across this [issue](https://github.com/bicarus-labs/near-api-rs/issues/1).
As you can see the OP, claims that this was being worked on to be less low level as per my understanding.
I would like some perspective to this. Thank you.

**Comment by miraclx** [comment]
Hi @Borwe, yeah, we resolved to keeping this crate as-is. Which in a sense is low-level.

So depending on your needs, this crate might be perfect for you. Otherwise, if you need something more approachable, consider https://github.com/near/workspaces-rs which is a higher-level API built on top of this client.
