### ISSUE TITLE
difference between `near 0.1` and `near 0.5` on `docs.rs`?

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-jsonrpc-client-rs#27]

**Comment by evergreen-trading-systems** [comment]
https://lib.rs/crates/near-chain-primitives

NEAR master branch doesn't show 0.5

**Comment by evergreen-trading-systems** [comment]
a better question is where can i be kept up to date with these kinds of changes?

**Comment by miraclx** [comment]
Hi, @evergreen-trading-systems, sorry for the delayed response.

First thing to note is: we recently finalized the implementation of and deployed an automated system for versioning and publishing [nearcore](https://github.com/near/nearcore) crates directly off the latest state of master branch (See https://github.com/near/nearcore/pull/5130).

So far, only [`v0.10.0`](https://github.com/near/nearcore/releases/tag/crates-0.10.0) has been cut with this new system. The prior `v0.1` and `v0.5` releases were cut manually. I recommend upgrading to `v0.10.0` where you can.

It's also worth noting that versioning in nearcore crates don't follow traditional semver rules.

All crates on the [nearcore](https://github.com/near/nearcore) repo share the same [version](https://github.com/near/nearcore/blob/b1cff67cea8f102f3748152dc9ea3c21d9b295d6/Cargo.toml#L51) and are all published at the same time whenever that workspace version is bumped, regardless of whether any individual crate changed since the last release or not.

And, by staying on `v0.x`, we make no guarantees of providing a stable API, nor guaranteeing backwards compatibility, although, that's not to say that we would intentionally break things.

To aid version cross-referencing between crates.io and GitHub, we appropriately tag the commit that the crates were published from. (See https://github.com/near/nearcore/releases/tag/crates-0.10.0)

And, to answer your question, tracking changes between versions, you can use this neat GitHub trick: `https://github.com/near/nearcore/compare/<tag-1>...<tag-2>`. For example: https://github.com/near/nearcore/compare/crates-0.10.0...master.

Unfortunately, as of the time of writing, there's no individual changelog for each crate, so you can't see what's changed beyond stepping through the diff. Which, while nice to have, isn't the best way to see changes.
