### ISSUE TITLE
`UNKNOWN_BLOCK` is represented as `TransportError`

### ISSUE THREAD

**Issue by nikurt** [near/near-jsonrpc-client-rs#28]
Call this request

```
RpcStateChangesInBlockByTypeRequest { block_reference: BlockId(Height(42376889)), state_changes_request: AccountChanges { account_ids: [AccountId("nkurtov-test1.testnet")] } }
```

Get  error

```
TransportError(
        RecvError(
            ResponseParseError(
                ErrorMessageParseError(
                    Error("missing field `error_message`", line: 0, column: 0),
                ),
            ),
        ),
    )
```

Doing the same using HTTPie I get an `UNKNOWN_BLOCK` error

```
% http post https://archival-rpc.testnet.near.org jsonrpc=2.0 method=EXPERIMENTAL_changes params:='{"changes_type":"account_changes","account_ids":["nkurtov-test1.testnet"],"block_id":42376889}' id=dontcare
HTTP/1.1 200 OK
Alt-Svc: clear
Content-Encoding: gzip
Content-Type: application/json
Date: Sun, 21 Nov 2021 23:25:39 GMT
Server: nginx/1.18.0 (Ubuntu)
Transfer-Encoding: chunked
Vary: Accept-Encoding
Via: 1.1 google
access-control-allow-origin:

{
    "error": {
        "cause": {
            "info": {},
            "name": "UNKNOWN_BLOCK"
        },
        "code": -32000,
        "data": {
            "info": {},
            "name": "UNKNOWN_BLOCK"
        },
        "message": "Server error",
        "name": "HANDLER_ERROR"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

**Comment by miraclx** [comment]
Indeed, the `UnknownBlock` variant of `RpcStateChangesError` isn't serialized with an `error_message` that is expected when deserializing: https://github.com/near/nearcore/blob/6f2a290227f4f3b41c543b615231e769e438e28c/chain/jsonrpc-primitives/src/types/changes.rs#L35. Likely because the contents of that field either isn't relevant externally, or isn't stable enough to be part of the public API.

For our use as a client, I'll introduce a shim that just returns an empty string for that field.

**Comment by frol** [comment]
@miraclx Yeah, we wanted to bring proper context into that variant and drop the error_message altogether since it is not machine-readable, and we did not want to expose it through API boundary. Ideally, there should be no `error_message` field on deserialization, which brings me to an idea of having a feature flag like "with_private_fields" that we would enable on the nearcore side for JSON RPC server, and don't enable in near-jsonrpc-client-rs; this approach will also fix our problems with `RpcTransactionError` (remember we needed to have extra handling there as well).

P.S. Check other `skip_serializing` places if any.

**Comment by frol** [comment]
Also, consider to add `default` to the `#[serialize(skip_serializing)]`, so it fills the field with an empty string in the worst case (when `with_private_fields` feature is enabled)

P.S. `with_private_fields` is not a great name, please, consider other names
